<?php

/**
 * @file
 * Contains loremipsum.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function loremipsum_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the loremipsum module.
    case 'help.page.loremipsum':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Lorem ipsum generator for Drupal') . '</p>';
      $output .= '<h3>' . t('Instructions') . '.</h3>';
      $output .= t( '
        <p>Lorem ipsum dolor sit amet... <strong>Just kidding!</strong></p>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/loremipsum</strong> and enter your own set of phrases to build random-generated text (or go with the default Lorem ipsum).</p>
        <p>Last, visit <strong>www.example.com/loremipsum/generate/P/S</strong> where:</p>
        <ul>
          <li>
            <em>P</em>  is the number of <em>paragraphs</em>
          </li>
          <li>
            <em>S</em>  is the maximum number of <em>sentences</em>
          </li>
        </ul>
        <p>There is also a generator block in which you can choose how many paragraphs and
        phrases and it\'ll do the rest.</p>
        <p>If you need, there\'s also a specific <em>generate lorem ipsum</em> permission.</p>
        <h3>Attn.</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions, ok? Ok.</p>
      ');
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function loremipsum_theme() {
  return [
    'loremipsum' => [
      'render element' => 'children',
    ],
  ];
}
